fix(purefa_smtp): Fix KeyError when using user parameter for SMTP auth
Fixed bug where configuring SMTP with authentication caused:
  KeyError: 'user_name'

The code incorrectly referenced module.params['user_name'] instead of
module.params['user'] when comparing the current SMTP user setting.

Also fixed unit tests that incorrectly included 'user_name' in mock
params (not a valid Ansible parameter) and added regression test for
issue #990.

Fixes #990